
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration,classpath:com/ecommerce/filterproducts/infrastructure/adapter/db/migration

logging:
  level:
    root: INFO

